# Generated by Django 5.1.8 on 2025-05-11 14:36

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='field2',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
