# Generated by Django 5.2.1 on 2025-05-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=30)),
                ('prenume', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('parola', models.CharField(max_length=32)),
                ('tip_persoana', models.CharField(max_length=10)),
                ('companie', models.CharField(max_length=60)),
                ('adresa', models.CharField(max_length=150)),
                ('status_cos', models.BooleanField()),
            ],
        ),
    ]
