# Generated by Django 5.2.1 on 2025-05-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='companie',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
